// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKCDXa4NQQQ7hSTeo4jJ4lV2dJ6NLmvuw',
    appId: '1:180845982486:web:231b5af25a668840679637',
    messagingSenderId: '180845982486',
    projectId: 'todochat-8993c',
    authDomain: 'todochat-8993c.firebaseapp.com',
    storageBucket: 'todochat-8993c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCebU30PHRdtng5KWg7lvDHRpClg4WwuiI',
    appId: '1:180845982486:android:3f6f409544fe351d679637',
    messagingSenderId: '180845982486',
    projectId: 'todochat-8993c',
    storageBucket: 'todochat-8993c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4FfYPOSdpnmy0Bw3dklrRF9zy-HrfLQI',
    appId: '1:180845982486:ios:fae7a0942789ff8c679637',
    messagingSenderId: '180845982486',
    projectId: 'todochat-8993c',
    storageBucket: 'todochat-8993c.appspot.com',
    iosBundleId: 'com.example.todochat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKCDXa4NQQQ7hSTeo4jJ4lV2dJ6NLmvuw',
    appId: '1:180845982486:web:b20edf160de55466679637',
    messagingSenderId: '180845982486',
    projectId: 'todochat-8993c',
    authDomain: 'todochat-8993c.firebaseapp.com',
    storageBucket: 'todochat-8993c.appspot.com',
  );
}
